"""Export state-transition traces and paper artefacts."""

from __future__ import annotations

import json
from pathlib import Path

from dualexis.sssg.metrics import StateGraphMetrics, compute_state_graph_metrics
from dualexis.sssg.models import StateTransitionTrace


def export_trace_json(trace: StateTransitionTrace, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = trace.model_dump(mode="json")
    path.write_text(json.dumps(payload, indent=2, default=str), encoding="utf-8")


def export_trace_csv_rows(trace: StateTransitionTrace) -> list[dict[str, str | int | float]]:
    rows: list[dict[str, str | int | float]] = []
    for transition in trace.transitions:
        rows.append(
            {
                "scenario_id": trace.scenario_id,
                "seed": trace.seed,
                "zone_id": transition.zone_id,
                "tick": transition.tick,
                "from_state": transition.from_state.value,
                "to_state": transition.to_state.value,
                "explanation": transition.explanation,
                "evidence_count": len(transition.evidence),
                "causal_edges": len(transition.causal_edge_ids),
                "corroborative_edges": len(transition.corroborative_edge_ids),
            }
        )
    return rows


def _tex_identifier(value: str) -> str:
    """Escape underscores for LaTeX text mode (state names, scenario ids)."""
    return value.replace("_", r"\_")


def write_state_transition_examples_tex(
    traces: list[StateTransitionTrace],
    metrics_by_scenario: dict[str, StateGraphMetrics],
    path: Path,
) -> None:
    """Generate LaTeX table of example state transitions."""
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "% Auto-generated by dualexis SSSG export.",
        "% State-transition examples (synthetic harness).",
        "",
        "\\begin{table}[htbp]",
        "  \\centering",
        "  \\caption{Example semantic safety state transitions (SSSG). "
        "Explanations are state-transition narratives, not event-only text.}",
        "  \\label{tab:state-transition-examples}",
        "  \\small",
        "  \\begin{tabular}{@{}llllp{5.2cm}@{}}",
        "    \\toprule",
        "    Scenario & Zone & From $\\rightarrow$ To & Tick & Explanation (excerpt) \\\\",
        "    \\midrule",
    ]
    shown = 0
    for trace in traces:
        for transition in trace.transitions[:2]:
            if shown >= 6:
                break
            excerpt = transition.explanation[:120].replace("_", "\\_")
            if len(transition.explanation) > 120:
                excerpt += "\\ldots"
            from_state = _tex_identifier(transition.from_state.value)
            to_state = _tex_identifier(transition.to_state.value)
            lines.append(
                f"    {_tex_identifier(trace.scenario_id)} & "
                f"{_tex_identifier(transition.zone_id)} & "
                f"\\texttt{{{from_state}}} $\\rightarrow$ \\texttt{{{to_state}}} & "
                f"{transition.tick} & "
                f"\\texttt{{\\footnotesize {excerpt}}} \\\\"
            )
            shown += 1
    if shown == 0:
        lines.append(
            "    \\multicolumn{5}{c}{\\textit{No transitions recorded in sample runs.}} \\\\"
        )
    lines.extend(
        [
            "    \\midrule",
            "    \\multicolumn{5}{l}{\\textbf{Aggregate metrics (mean over scenarios):}} \\\\",
        ]
    )
    if metrics_by_scenario:
        mean_tp = sum(m.transition_precision for m in metrics_by_scenario.values()) / len(
            metrics_by_scenario
        )
        mean_tr = sum(m.transition_recall for m in metrics_by_scenario.values()) / len(
            metrics_by_scenario
        )
        mean_sc = sum(m.state_consistency for m in metrics_by_scenario.values()) / len(
            metrics_by_scenario
        )
        mean_cc = sum(m.causal_trace_completeness for m in metrics_by_scenario.values()) / len(
            metrics_by_scenario
        )
        lines.append(
            f"    \\multicolumn{{5}}{{l}}{{"
            f"transition precision={mean_tp:.2f}; "
            f"recall={mean_tr:.2f}; "
            f"state consistency={mean_sc:.2f}; "
            f"causal trace completeness={mean_cc:.2f}}} \\\\"
        )
    lines.extend(["    \\bottomrule", "  \\end{tabular}", "\\end{table}", ""])
    path.write_text("\n".join(lines), encoding="utf-8")


def generate_semantic_state_graph_pdf(path: Path) -> None:
    """Compile schematic SSSG figure from TikZ (no matplotlib dependency)."""
    import shutil
    import subprocess

    path.parent.mkdir(parents=True, exist_ok=True)
    repo_root = Path(__file__).resolve().parents[2]
    tex_source = repo_root / "paper" / "figures" / "semantic_state_graph.tex"
    if not tex_source.is_file():
        msg = f"Missing TikZ source: {tex_source}"
        raise FileNotFoundError(msg)

    work_dir = path.parent
    build_copy = work_dir / "semantic_state_graph_build.tex"
    build_copy.write_text(tex_source.read_text(encoding="utf-8"), encoding="utf-8")
    pdflatex = shutil.which("pdflatex")
    if pdflatex is None:
        # Fallback: copy pre-authored tex next to target for manual build
        shutil.copy(tex_source, work_dir / "semantic_state_graph.tex")
        if not path.exists():
            path.write_bytes(b"% PDF placeholder - run pdflatex on semantic_state_graph.tex\n")
        return

    subprocess.run(
        [pdflatex, "-interaction=nonstopmode", "-halt-on-error", build_copy.name],
        cwd=work_dir,
        check=True,
        capture_output=True,
    )
    built = work_dir / "semantic_state_graph_build.pdf"
    if built.is_file():
        built.replace(path)
    aux_suffixes = (".aux", ".log", ".pdf")
    for suffix in aux_suffixes:
        extra = work_dir / f"semantic_state_graph_build{suffix}"
        if extra.is_file() and suffix != ".pdf":
            extra.unlink(missing_ok=True)


__all__ = [
    "export_trace_csv_rows",
    "export_trace_json",
    "generate_semantic_state_graph_pdf",
    "write_state_transition_examples_tex",
]
