"""LaTeX export for leakage audit paper artefacts."""

from __future__ import annotations

from pathlib import Path

from dualexis.leakage_audit.models import LeakageAuditReport
from dualexis.leakage_audit.monte_carlo import MonteCarloScenarioResult


def write_leakage_audit_tex(
    report: LeakageAuditReport,
    mc_results: dict[str, MonteCarloScenarioResult],
    path: Path,
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "% Auto-generated by dualexis leakage audit.",
        "",
        "\\begin{table}[htbp]",
        "  \\centering",
        "  \\caption{E2 leakage audit: structural overlap and independence estimates "
        f"($N_{{\\mathrm{{MC}}}}={report.monte_carlo_iterations}$ threshold perturbations).}}",
        "  \\label{tab:leakage-audit}",
        "  \\small",
        "  \\begin{tabular}{@{}lr@{}}",
        "    \\toprule",
        "    Metric & Value \\\\",
        "    \\midrule",
        f"    Shared variables ratio & {report.overlap.shared_variables_ratio:.3f} \\\\",
        f"    Shared threshold ratio & {report.overlap.shared_threshold_ratio:.3f} \\\\",
        f"    Shared logic ratio & {report.overlap.shared_logic_ratio:.3f} \\\\",
        f"    Leakage score $L_S$ (higher = more coupling) & {report.leakage_score:.3f} \\\\",
        "    \\midrule",
        f"    Procedural independence & {report.independence.procedural_independence:.3f} \\\\",
        f"    Semantic independence & {report.independence.semantic_independence:.3f} \\\\",
        f"    Distributional independence & {report.independence.distributional_independence:.3f} \\\\",
        "    \\midrule",
        f"    GT stability (MC mean) & {report.ground_truth_stability_mean:.3f} \\\\",
        f"    Event stability (MC mean) & {report.event_stability_mean:.3f} \\\\",
        f"    Agreement drift (MC mean) & {report.agreement_drift_mean:.3f} \\\\",
        "    \\bottomrule",
        "  \\end{tabular}",
        "\\end{table}",
        "",
        "\\begin{table}[htbp]",
        "  \\centering",
        "  \\caption{Monte Carlo sensitivity by scenario (threshold perturbations on GT rules).}",
        "  \\label{tab:leakage-mc-by-scenario}",
        "  \\small",
        "  \\begin{tabular}{@{}lrrr@{}}",
        "    \\toprule",
        "    Scenario & GT stability & Event stability & Agreement drift \\\\",
        "    \\midrule",
    ]
    for scenario, mc in sorted(mc_results.items()):
        lines.append(
            f"    {scenario.replace('_', '\\_')} & {mc.ground_truth_stability:.3f} & "
            f"{mc.event_stability:.3f} & {mc.agreement_drift:.3f} \\\\"
        )
    lines.extend(["    \\bottomrule", "  \\end{tabular}", "\\end{table}", ""])
    path.write_text("\n".join(lines), encoding="utf-8")


def write_leakage_analysis_section(report: LeakageAuditReport, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    content = f"""\\subsection{{E2 Leakage Audit Methodology}}
\\label{{sec:leakage-analysis}}

Independent ground truth (E2) is evaluated with a \\textbf{{leakage audit framework}} that quantifies
coupling among \\texttt{{world\\_dynamics}}, \\texttt{{event\\_generator}}, and
\\texttt{{ground\\_truth\\_rules}}. The audit does not replace field validation; it documents
\\emph{{where}} benchmark conclusions may inherit synthetic coupling.

\\paragraph{{Structural overlap.}}
We extract canonical variables (zone density, activity, audio, exit throughput), threshold
predicates, and scenario guards from each component. Table~\\ref{{tab:leakage-audit}} reports:
\\textbf{{shared\\_variables\\_ratio}} (Jaccard on variable sets),
\\textbf{{shared\\_threshold\\_ratio}} (bucket alignment plus generator--rules semantic match),
and \\textbf{{shared\\_logic\\_ratio}} (Jaccard on normalized logic predicates).
The composite \\textbf{{leakage score}} $L_S \\in [0,1]$ combines these overlaps (higher indicates
greater shared coupling).

\\paragraph{{Independence layers.}}
\\begin{{itemize}}[noitemsep]
  \\item \\textbf{{Procedural independence}} --- AST-confirmed absence of
        \\texttt{{event\\_generator}} imports in \\texttt{{independent\\_labeler}} (score=
        {report.independence.procedural_independence:.2f}).
  \\item \\textbf{{Semantic independence}} --- $1 - $ mean structural overlap (score=
        {report.independence.semantic_independence:.2f}).
  \\item \\textbf{{Distributional independence}} --- Monte Carlo stability of labels and
        agreement under random threshold perturbations (score=
        {report.independence.distributional_independence:.2f}).
\\end{{itemize}}

\\paragraph{{Monte Carlo sensitivity.}}
We draw $N_{{\\mathrm{{MC}}}}={report.monte_carlo_iterations}$ perturbations scaling each GT rule
threshold by $U(0.88, 1.12)$ and measure:
(i)~\\emph{{ground-truth stability}} (label multiset overlap),
(ii)~\\emph{{event stability}} (generator outputs under fixed seed; expected $\\approx 1.0$ when
only GT rules move),
(iii)~\\emph{{agreement drift}} (change in event--GT agreement).
Scenario-level results appear in Table~\\ref{{tab:leakage-mc-by-scenario}}.

\\paragraph{{Dependency graph.}}
A Graphviz dependency graph (\\texttt{{results/leakage\\_audit/dependency\\_graph.dot}}) links
components by shared metrics and threshold alignment edges.

\\paragraph{{Benchmark disclosure.}}
\\begin{{quote}}
\\textbf{{{report.benchmark_disclosure}}}
\\end{{quote}}

\\input{{tables/leakage_audit}}
"""
    path.write_text(content, encoding="utf-8")


__all__ = ["write_leakage_analysis_section", "write_leakage_audit_tex"]
