"""LaTeX export for Human-AI governance evaluation."""

from __future__ import annotations

from pathlib import Path

from dualexis.governance.models import GovernanceEvaluationReport, ProfileGovernanceMetrics


def write_governance_metrics_tex(report: GovernanceEvaluationReport, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "% Auto-generated by dualexis governance evaluation.",
        "",
        "\\begin{table}[htbp]",
        "  \\centering",
        "  \\caption{Human-AI governance metrics by simulated operator profile "
        f"($N={report.simulation_iterations}$ review decisions per profile).}}",
        "  \\label{tab:governance-metrics}",
        "  \\small",
        "  \\begin{tabular}{@{}lrrrrrrrr@{}}",
        "    \\toprule",
        "    Profile & Accept & Override & Escalate & Dismiss & Latency (s) & "
        "$R_{\\mathrm{auto}}$ & $R_{\\mathrm{under}}$ & $R_{\\mathrm{over}}$ \\\\",
        "    \\midrule",
    ]
    for metrics in report.profile_metrics:
        lines.append(_metrics_row(metrics))
    lines.extend(
        [
            "    \\bottomrule",
            "  \\end{tabular}",
            "\\end{table}",
            "",
            "\\begin{table}[htbp]",
            "  \\centering",
            "  \\caption{Governance risk decomposition (automation bias, under-reliance, over-reliance).}",
            "  \\label{tab:governance-risks}",
            "  \\small",
            "  \\begin{tabular}{@{}lrrr@{}}",
            "    \\toprule",
            "    Profile & Automation bias & Under-reliance & Over-reliance \\\\",
            "    \\midrule",
        ]
    )
    for metrics in report.profile_metrics:
        lines.append(
            f"    {metrics.profile.value} & "
            f"{metrics.bias_risks.automation_bias_risk:.3f} & "
            f"{metrics.bias_risks.under_reliance_risk:.3f} & "
            f"{metrics.bias_risks.over_reliance_risk:.3f} \\\\"
        )
    lines.extend(["    \\bottomrule", "  \\end{tabular}", "\\end{table}", ""])
    path.write_text("\n".join(lines), encoding="utf-8")


def _metrics_row(metrics: ProfileGovernanceMetrics) -> str:
    return (
        f"    {metrics.profile.value} & "
        f"{metrics.acceptance_rate:.3f} & "
        f"{metrics.override_rate:.3f} & "
        f"{metrics.escalation_rate:.3f} & "
        f"{metrics.dismissal_rate:.3f} & "
        f"{metrics.mean_review_latency_seconds:.1f} & "
        f"{metrics.bias_risks.automation_bias_risk:.3f} & "
        f"{metrics.bias_risks.under_reliance_risk:.3f} & "
        f"{metrics.bias_risks.over_reliance_risk:.3f} \\\\"
    )


def write_governance_evaluation_section(report: GovernanceEvaluationReport, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    balanced = next(m for m in report.profile_metrics if m.profile.value == "balanced")
    conservative = next(m for m in report.profile_metrics if m.profile.value == "conservative")
    aggressive = next(m for m in report.profile_metrics if m.profile.value == "aggressive")

    content = f"""\\subsection{{Human-AI Governance Layer}}
\\label{{sec:governance-evaluation}}

DUALEXIS extends advisory orchestration with a formal \\textbf{{{report.contribution_title}}}.
Unlike informal ``human review required'' flags, governance is modeled as an explicit
state machine over operator decisions with measurable reliance risks.

\\paragraph{{Governance states.}}
Each recommendation enters \\texttt{{PENDING\\_REVIEW}} and transitions to a terminal state:
\\texttt{{REVIEWED}} (accept), \\texttt{{OVERRIDDEN}}, \\texttt{{ESCALATED}}, or
\\texttt{{DISMISSED}}. The Graphviz artefact
\\texttt{{results/governance/governance\\_graph.dot}} documents allowed transitions.

\\paragraph{{Operator decision model.}}
We simulate three operator profiles---\\emph{{conservative}}, \\emph{{balanced}}, and
\\emph{{aggressive}}---with distinct acceptance, override, escalation, and latency parameters.
Each profile processes $N={report.simulation_iterations}$ review decisions sampled from pipeline
recommendations across {report.case_pool_size} harvested cases (resampled with replacement).

\\paragraph{{Governance metrics.}}
Table~\\ref{{tab:governance-metrics}} reports acceptance rate, override rate, escalation rate,
mean review latency, and reliance risks. For the balanced profile: acceptance=
{balanced.acceptance_rate:.2f}, override={balanced.override_rate:.2f}, escalation=
{balanced.escalation_rate:.2f}, mean latency={balanced.mean_review_latency_seconds:.0f}\\,s.
Conservative operators show higher escalation ({conservative.escalation_rate:.2f}) and longer
latency ({conservative.mean_review_latency_seconds:.0f}\\,s); aggressive profiles elevate override
({aggressive.override_rate:.2f}) and over-reliance risk ({aggressive.bias_risks.over_reliance_risk:.2f}).

\\paragraph{{Reliance risks.}}
\\begin{{itemize}}[noitemsep]
  \\item \\textbf{{Automation bias risk}} --- excess acceptance of incorrect high-confidence AI advice.
  \\item \\textbf{{Under-reliance risk}} --- override/escalation when AI matches the scenario oracle.
  \\item \\textbf{{Over-reliance risk}} --- acceptance when AI diverges from the oracle action.
\\end{{itemize}}
Table~\\ref{{tab:governance-risks}} decomposes these risks by profile.

\\paragraph{{Positioning.}}
The governance layer separates \\emph{{advisory automation}} (L4--L5) from
\\emph{{accountable disposition}} (L6), enabling institutions to audit acceptance compliance,
override patterns, and escalation discipline before pilot deployment.

\\input{{tables/governance_metrics}}
"""
    path.write_text(content, encoding="utf-8")


__all__ = ["write_governance_evaluation_section", "write_governance_metrics_tex"]
