"""TSGG paper artefacts: figure, tables, unified section."""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

from dualexis.tsgg.formulation import build_tsgg_formulation_block
from dualexis.tsgg.models import TsggFrameworkReport, TsggUnifiedMetrics


def write_tsgg_unified_metrics_table(metrics: TsggUnifiedMetrics, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    rows = [
        ("Transition precision $P_{\\mathrm{prec}}$", metrics.transition_precision),
        ("Transition recall $P_{\\mathrm{rec}}$", metrics.transition_recall),
        ("Causal path completeness $\\Pi_{\\mathrm{causal}}$", metrics.causal_path_completeness),
        ("Leakage score $L_S$", metrics.leakage_score),
        ("Procedural independence $\\pi_{\\mathrm{proc}}$", metrics.procedural_independence),
        ("Distributional independence $\\pi_{\\mathrm{dist}}$", metrics.distributional_independence),
        ("Governance compliance $\\gamma_{\\mathrm{comp}}$", metrics.governance_compliance_score),
        ("Decision traceability $\\tau_{\\mathrm{trace}}$", metrics.decision_traceability),
        ("TSGG trust index $\\mathcal{I}_{\\mathrm{TSGG}}$", metrics.tsgg_trust_index),
    ]
    lines = [
        "% Auto-generated by dualexis TSGG export",
        "\\begin{table}[htbp]",
        "  \\centering",
        "  \\caption{Unified TSGG metrics (state, causal, benchmark trust, governance). "
        "Governance terms $\\gamma_{\\mathrm{comp}}$ and $\\tau_{\\mathrm{trace}}$ are taken "
        "from the formal FSM audit (Section~\\ref{sec:formal-governance-model}).}",
        "  \\label{tab:tsgg-unified-metrics}",
        "  \\small",
        "  \\begin{tabular}{@{}lr@{}}",
        "    \\toprule",
        "    Metric & Value \\\\",
        "    \\midrule",
    ]
    for label, value in rows:
        lines.append(f"    {label} & {value:.3f} \\\\")
    lines.extend(
        [
            "    \\bottomrule",
            "  \\end{tabular}",
            "\\end{table}",
            "",
        ]
    )
    path.write_text("\n".join(lines), encoding="utf-8")


def write_tsgg_framework_section(report: TsggFrameworkReport, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    m = report.unified_metrics
    formulation = build_tsgg_formulation_block(m)
    stage_labels = (
        "evidence",
        "safety state",
        "causal transition",
        "recommendation",
        "governance decision",
        "audit trace",
    )
    stages = " $\\rightarrow$ ".join(stage_labels)

    content = f"""\\section{{Trusted Safety State Governance Graph (TSGG)}}
\\label{{sec:tsgg}}

DUALEXIS contributes a \\textbf{{single scientific artefact}}---the Trusted Safety State
Governance Graph (TSGG)---that unifies semantic safety-state reasoning (SSSG), benchmark
leakage auditing, and formal human--AI governance into one auditable pipeline. Prior
decompositions treated these as independent engineering modules; TSGG positions them as
\\emph{{stages of one trust-bearing decision trace}}.

\\paragraph{{Pipeline.}}
The end-to-end chain is:
\\emph{{{stages}}}.
Figure~\\ref{{fig:tsgg-framework}} summarises the architecture; Section~\\ref{{sec:tsgg-theory}}
states the formal theory (axioms, invariants, propositions); Equations~\\eqref{{eq:tsgg-pipeline}}
and~\\eqref{{eq:tsgg-trust}} provide the operational reporting formulation.

\\input{{sections/tsgg_figure}}
\\input{{tables/tsgg_unified_metrics}}

{formulation}

\\paragraph{{Stage semantics.}}
\\begin{{itemize}}[noitemsep]
  \\item \\textbf{{Evidence ($E$).}} Privacy-bounded observations ingested from the synthetic
        world and event generator (L1--L3).
  \\item \\textbf{{Safety state ($S$).}} Zone-scoped semantic labels
        (\\texttt{{NORMAL}} $\\rightarrow$ \\texttt{{EVACUATION\\_CANDIDATE}}) with temporal edges.
  \\item \\textbf{{Causal transition ($C$).}} Typed causal factors and root-cause attribution
        (CSSG backbone inside TSGG).
  \\item \\textbf{{Recommendation ($R$).}} Orchestration advisories with mandatory human review
        for elevated severities.
  \\item \\textbf{{Governance decision ($G$).}} Macro-state FSM
        $S_{{\\mathrm{{gov}}}}=\\{{s^{{AI}}, s^{{H}}, s^{{I}}\\}}$ with transition alphabet
        $\\Sigma$.
  \\item \\textbf{{Audit trace ($A$).}} Append-only $(s,\\sigma,s')$ chains for institutional review.
\\end{{itemize}}

\\paragraph{{Benchmark trust.}}
The leakage audit supplies $L_S$ and independence estimates $\\pi_{{\\mathrm{{proc}}}}$,
$\\pi_{{\\mathrm{{dist}}}}$ as \\emph{{external}} trust constraints on the evaluation harness---
not as a separate paper contribution. Low $L_S$ with high independence supports interpreting
state and governance metrics as non-leaking descriptive evidence.

\\paragraph{{Trust-aware reasoning.}}
Vertex-level trust propagation (Section~\\ref{{sec:trust-propagation}}) assigns
$T(v)\\in[0,1]$ to every TSGG node with operators
$\\rho,\\sigma,\\kappa,\\omega,\\delta,\\alpha$, yielding path trust $T(\\pi)$ and
trust-theoretic metrics (consistency, decay, recovery) beyond the composite
$\\mathcal{{I}}_{{\\mathrm{{TSGG}}}}$.

\\paragraph{{Positioning.}}
TSGG subsumes SSSG (state graph), CSSG (causal layer), E2 leakage audit, and the formal
governance FSM as a \\textbf{{trust-aware reasoning graph}}. Implementation modules remain in
\\texttt{{dualexis/sssg}}, \\texttt{{dualexis/cssg}}, \\texttt{{dualexis/leakage\\_audit}},
\\texttt{{dualexis/governance}}, and \\texttt{{dualexis/tsgg/trust\\_propagation.py}}.
{report.disclaimer}
"""
    path.write_text(content, encoding="utf-8")


def generate_tsgg_framework_pdf(path: Path) -> None:
    """Compile standalone TikZ figure for TSGG."""
    path.parent.mkdir(parents=True, exist_ok=True)
    repo_root = Path(__file__).resolve().parents[2]
    tex_source = Path(__file__).resolve().parent / "assets" / "tsgg_framework.tex"
    if not tex_source.is_file():
        msg = f"Missing TikZ source: {tex_source}"
        raise FileNotFoundError(msg)

    work_dir = path.parent
    build_copy = work_dir / "tsgg_framework_build.tex"
    build_copy.write_text(tex_source.read_text(encoding="utf-8"), encoding="utf-8")
    pdflatex = shutil.which("pdflatex")
    if pdflatex is None:
        shutil.copy(tex_source, work_dir / "tsgg_framework.tex")
        if not path.exists():
            path.write_bytes(b"% PDF placeholder - run pdflatex on tsgg_framework.tex\n")
        return

    subprocess.run(
        [pdflatex, "-interaction=nonstopmode", "-halt-on-error", build_copy.name],
        cwd=work_dir,
        check=False,
        capture_output=True,
    )
    built = work_dir / "tsgg_framework_build.pdf"
    if built.is_file():
        shutil.copy(built, path)
    elif (work_dir / "tsgg_framework.pdf").is_file():
        shutil.copy(work_dir / "tsgg_framework.pdf", path)


def write_tsgg_figure_include(path: Path) -> None:
    """LaTeX snippet to include TSGG figure in main paper."""
    path.parent.mkdir(parents=True, exist_ok=True)
    content = """\\begin{figure}[htbp]
  \\centering
  \\includegraphics[width=\\linewidth]{figures/tsgg_framework.pdf}
  \\caption{TSGG unified pipeline: evidence through audit trace, with benchmark trust
    constraints feeding the composite trust index $\\mathcal{I}_{\\mathrm{TSGG}}$.}
  \\label{fig:tsgg-framework}
\\end{figure}
"""
    path.write_text(content, encoding="utf-8")


__all__ = [
    "generate_tsgg_framework_pdf",
    "write_tsgg_figure_include",
    "write_tsgg_framework_section",
    "write_tsgg_unified_metrics_table",
]
