"""LaTeX and PDF export for CSSG paper artefacts."""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

from dualexis.cssg.chains import build_explanation_chain, canonical_escalation_chain_text
from dualexis.cssg.metrics import CausalGraphMetrics
from dualexis.cssg.models import CausalStateTransitionTrace


def _tex_identifier(value: str) -> str:
    return value.replace("_", r"\_")


def write_causal_metrics_tex(
    metrics_by_scenario: dict[str, CausalGraphMetrics],
    stability_by_scenario: dict[str, float],
    path: Path,
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "% Auto-generated by dualexis CSSG export.",
        "",
        "\\begin{table}[htbp]",
        "  \\centering",
        "  \\caption{Causal Safety State Graph (CSSG) metrics by scenario "
        "(mean over seeds). CSSG extends SSSG with typed causal edges and root-cause paths.}",
        "  \\label{tab:causal-metrics}",
        "  \\small",
        "  \\begin{tabular}{@{}lrrrrrr@{}}",
        "    \\toprule",
        "    Scenario & Depth & Root prec. & Path compl. & Trace compl. & "
        "Trans. prec. & Stability \\\\",
        "    \\midrule",
    ]
    for scenario, metrics in sorted(metrics_by_scenario.items()):
        stability = stability_by_scenario.get(scenario, metrics.explanation_stability_across_seeds)
        lines.append(
            f"    {_tex_identifier(scenario)} & "
            f"{metrics.causal_explanation_depth:.2f} & "
            f"{metrics.root_cause_precision:.2f} & "
            f"{metrics.causal_path_completeness:.2f} & "
            f"{metrics.causal_trace_completeness:.2f} & "
            f"{metrics.transition_precision:.2f} & "
            f"{stability:.2f} \\\\"
        )
    lines.extend(["    \\bottomrule", "  \\end{tabular}", "\\end{table}", ""])
    path.write_text("\n".join(lines), encoding="utf-8")


def write_causal_reasoning_section(
    *,
    example_chain: str,
    path: Path,
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    escaped_chain = example_chain.replace("\n", "\\\\\n    ")
    content = f"""\\subsection{{Causal Safety State Graph (CSSG)}}
\\label{{sec:causal-reasoning}}

DUALEXIS advances the Semantic Safety State Graph (SSSG) into a \\textbf{{Causal Safety State Graph
(CSSG)}}---a novel \\emph{{explainable safety reasoning}} framework. Unlike temporal event graphs
that only sequence observations, CSSG attributes each safety-state transition to typed causal
mechanisms with confidence, supporting evidence, and explicit alternative hypotheses.

\\paragraph{{Positioning.}}
Event-centric pipelines answer \\emph{{what happened}}; CSSG answers \\emph{{why the safety state
changed}} and \\emph{{which root factors warrant staff attention}}. Recommendations remain advisory;
CSSG supplies auditable causal chains for human disposition (Section~\\ref{{sec:governance-evaluation}}).

\\paragraph{{Typed causal edges.}}
CSSG edges are labelled \\texttt{{contributes\\_to}}, \\texttt{{aggravates}}, \\texttt{{mitigates}},
or \\texttt{{triggers}}, replacing generic ``causal'' arcs in SSSG. Each transition stores:
\\textbf{{causal\\_factors}}, \\textbf{{confidence}}, \\textbf{{supporting\\_evidence}}, and
\\textbf{{alternative\\_explanations}}.

\\paragraph{{Root-cause extraction.}}
The function \\texttt{{find\\_root\\_causes(zone\\_id, tick)}} walks backward along zone transitions
to surface primary \\texttt{{contributes\\_to}} / \\texttt{{triggers}} factors---the earliest
explainable drivers, not merely the latest alert.

\\paragraph{{Causal metrics.}}
Table~\\ref{{tab:causal-metrics}} reports \\textbf{{causal\\_explanation\\_depth}},
\\textbf{{root\\_cause\\_precision}}, \\textbf{{causal\\_path\\_completeness}}, and
\\textbf{{explanation\\_stability\\_across\\_seeds}} (Jaccard overlap of chain signatures under
seed perturbation).

\\paragraph{{Example explanation chain.}}
\\begin{{verbatim}}
{escaped_chain}
\\end{{verbatim}}

\\begin{{figure}}[htbp]
  \\centering
  \\includegraphics[width=0.92\\linewidth]{{figures/causal_state_graph.pdf}}
  \\caption{{Causal Safety State Graph (CSSG): typed causal edges (\\texttt{{contributes\\_to}},
            \\texttt{{aggravates}}, \\texttt{{triggers}}, \\texttt{{mitigates}}) over safety states.
            Dotted arcs indicate temporal progression; CSSG is a causal explanation framework, not an
            event timeline.}}
  \\label{{fig:causal-state-graph}}
\\end{{figure}}

\\input{{tables/causal_metrics}}
"""
    path.write_text(content, encoding="utf-8")


def write_causal_chain_figure_tex(path: Path) -> None:
    """Write standalone TikZ figure source for causal_state_graph.pdf."""
    path.parent.mkdir(parents=True, exist_ok=True)
    tex = r"""% Standalone CSSG schematic — compile: pdflatex causal_state_graph.tex
\documentclass[border=2pt]{standalone}
\usepackage{tikz}
\usetikzlibrary{arrows.meta,positioning}

\begin{document}
\begin{tikzpicture}[
  state/.style={draw, rounded corners=2pt, minimum width=1.55cm, minimum height=0.7cm,
                align=center, font=\footnotesize\bfseries, fill=blue!8},
  contributes/.style={-{Stealth[length=2mm]}, draw=orange!80!black, thick},
  aggravates/.style={-{Stealth[length=2mm]}, draw=red!70!black, thick},
  triggers/.style={-{Stealth[length=2mm]}, draw=purple!70!black, very thick},
  mitigates/.style={-{Stealth[length=2mm]}, draw=green!50!black, dashed},
  temporal/.style={-{Stealth[length=2mm]}, draw=blue!50!black, thick, dotted},
]

\node[state] (normal) at (0,0) {NORMAL};
\node[state] (crowd) at (2.8,1.3) {CROWDING\\RISK};
\node[state] (exit) at (5.6,0) {EXIT\\IMPAIRMENT};
\node[state] (evac) at (8.4,0) {EVACUATION\\CANDIDATE};

\draw[contributes] (normal) to node[above, font=\scriptsize] {contributes\_to} (crowd);
\draw[aggravates] (crowd) to node[above, font=\scriptsize] {aggravates} (exit);
\draw[triggers] (exit) to node[above, font=\scriptsize] {triggers} (evac);
\draw[temporal] (normal) to[bend right=40] node[below, font=\scriptsize] {temporal} (exit);
\draw[mitigates] (evac) to[bend left=25] node[below, font=\scriptsize] {mitigates} (crowd);

\node[font=\small\bfseries] at (4.2,2.2) {Causal Safety State Graph (CSSG)};
\node[font=\scriptsize, align=center] at (4.2,-1.5) {Orange=contributes\_to\quad Red=aggravates\\
Purple=triggers\quad Green dashed=mitigates\quad Blue dotted=temporal};

\end{tikzpicture}
\end{document}
"""
    path.write_text(tex, encoding="utf-8")


def generate_causal_state_graph_pdf(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    repo_root = Path(__file__).resolve().parents[2]
    tex_source = repo_root / "paper" / "figures" / "causal_state_graph.tex"
    if not tex_source.is_file():
        write_causal_chain_figure_tex(tex_source)
    work_dir = path.parent
    build_copy = work_dir / "causal_state_graph_build.tex"
    build_copy.write_text(tex_source.read_text(encoding="utf-8"), encoding="utf-8")
    pdflatex = shutil.which("pdflatex")
    if pdflatex is None:
        if not path.exists():
            path.write_bytes(b"% PDF placeholder - run pdflatex on causal_state_graph.tex\n")
        return
    subprocess.run(
        [pdflatex, "-interaction=nonstopmode", "-halt-on-error", build_copy.name],
        cwd=work_dir,
        check=True,
        capture_output=True,
    )
    built = work_dir / "causal_state_graph_build.pdf"
    if built.is_file():
        built.replace(path)
    for suffix in (".aux", ".log"):
        extra = work_dir / f"causal_state_graph_build{suffix}"
        extra.unlink(missing_ok=True)


def pick_example_chain(trace: CausalStateTransitionTrace) -> str:
    for zone in trace.zone_ids:
        chain = build_explanation_chain(trace, zone)
        if "EVACUATION_CANDIDATE" in chain or "EXIT_IMPAIRMENT" in chain:
            return chain
    return canonical_escalation_chain_text()


__all__ = [
    "generate_causal_state_graph_pdf",
    "pick_example_chain",
    "write_causal_chain_figure_tex",
    "write_causal_metrics_tex",
    "write_causal_reasoning_section",
]
