"""Unit tests for harness honesty Table 8 export."""

from __future__ import annotations

import csv
from pathlib import Path

import pytest

from dualexis.evaluation.harness_b5_alignment import (
    HarnessB5InputError,
    HarnessB5ScenarioRow,
    classify_detection_accuracy,
    load_harness_b5_alignment,
)
from dualexis.evaluation.harness_b5_labels_export import (
    AUTO_GENERATED_BANNER,
    export_harness_b5_labels_tex,
    render_harness_b5_labels_latex,
)
from dualexis.experiments.empirical_battery import PAPER_SCENARIOS

FIXTURE_CSV = Path(__file__).resolve().parents[1] / "fixtures" / "harness_b5" / "baseline_results.csv"


@pytest.mark.parametrize(
    ("mean_accuracy", "expected"),
    [
        (1.0, "Pass"),
        (0.0, "Fail"),
        (0.5, "Partial"),
        (0.3333, "Partial"),
    ],
)
def test_classify_detection_accuracy(mean_accuracy: float, expected: str) -> None:
    assert classify_detection_accuracy(mean_accuracy) == expected


@pytest.mark.unit
def test_classify_rejects_out_of_range() -> None:
    with pytest.raises(HarnessB5InputError, match="outside"):
        classify_detection_accuracy(1.5)


@pytest.mark.unit
def test_load_alignment_from_fixture() -> None:
    alignment = load_harness_b5_alignment(FIXTURE_CSV)
    assert len(alignment.rows) == len(PAPER_SCENARIOS)
    labels = {row.scenario: row.label for row in alignment.rows}
    assert all(label == "Pass" for label in labels.values())
    assert alignment.seed_count == 3


@pytest.mark.unit
def test_load_alignment_missing_csv(tmp_path: Path) -> None:
    with pytest.raises(HarnessB5InputError, match="validate-tsgg"):
        load_harness_b5_alignment(tmp_path / "missing.csv")


@pytest.mark.unit
def test_load_alignment_missing_scenario(tmp_path: Path) -> None:
    csv_path = tmp_path / "results.csv"
    with csv_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=[
                "paper_baseline",
                "scenario",
                "seed",
                "event_detection_accuracy",
            ],
        )
        writer.writeheader()
        writer.writerow(
            {
                "paper_baseline": "B5",
                "scenario": "normal_flow",
                "seed": 1,
                "event_detection_accuracy": 1.0,
            }
        )
    with pytest.raises(HarnessB5InputError, match="No B5 rows"):
        load_harness_b5_alignment(csv_path)


@pytest.mark.unit
def test_render_latex_structure() -> None:
    alignment_rows = tuple(
        HarnessB5ScenarioRow(
            scenario=scenario,
            mean_detection_accuracy=1.0 if scenario == "normal_flow" else 0.0,
            seed_count=30,
            label="Pass" if scenario == "normal_flow" else "Fail",
        )
        for scenario in PAPER_SCENARIOS
    )
    from dualexis.evaluation.harness_b5_alignment import HarnessB5Alignment

    tex = render_harness_b5_labels_latex(
        HarnessB5Alignment(paper_baseline="B5", rows=alignment_rows)
    )
    assert "\\label{tab:harness-b5-by-scenario}" in tex
    assert AUTO_GENERATED_BANNER.strip() in tex
    assert r"normal\_flow & Pass" in tex


@pytest.mark.unit
def test_export_writes_file(tmp_path: Path) -> None:
    out = tmp_path / "harness_b5_by_scenario.tex"
    alignment = load_harness_b5_alignment(FIXTURE_CSV)
    export_harness_b5_labels_tex(out, alignment=alignment)
    text = out.read_text(encoding="utf-8")
    assert text.startswith("% Auto-generated by dualexis evaluation harness_b5_labels_export.")
