"""Unit tests for harness honesty Table 7 export."""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from dualexis.evaluation.harness_honesty_export import (
    AUTO_GENERATED_BANNER,
    HarnessHonestyInputError,
    HarnessHonestyMetrics,
    HarnessHonestyPaths,
    export_harness_honesty_tex,
    load_harness_honesty_metrics,
    load_privacy_fuzz_pass_rate,
    render_harness_honesty_latex,
)

FIXTURES = Path(__file__).resolve().parents[1] / "fixtures" / "harness_honesty"


@pytest.mark.unit
def test_load_metrics_happy_path() -> None:
    paths = HarnessHonestyPaths(
        leakage_report=FIXTURES / "leakage_audit_report.json",
        privacy_fuzz_csv=FIXTURES / "privacy_fuzz_results.csv",
        governance_report=FIXTURES / "governance_audit_report.json",
        trust_report=FIXTURES / "trust_propagation_report.json",
    )
    metrics = load_harness_honesty_metrics(paths)
    assert metrics.leakage_score == pytest.approx(0.111)
    assert metrics.distributional_independence == pytest.approx(0.222)
    assert metrics.governance_compliance_score == pytest.approx(0.44)
    assert metrics.mean_path_trust == pytest.approx(0.333)


@pytest.mark.unit
def test_load_metrics_missing_leakage_file(tmp_path: Path) -> None:
    paths = HarnessHonestyPaths(
        leakage_report=tmp_path / "missing.json",
        privacy_fuzz_csv=FIXTURES / "privacy_fuzz_results.csv",
        governance_report=FIXTURES / "governance_audit_report.json",
        trust_report=FIXTURES / "trust_propagation_report.json",
    )
    with pytest.raises(HarnessHonestyInputError, match="leakage-audit"):
        load_harness_honesty_metrics(paths)


@pytest.mark.unit
def test_privacy_fuzz_wrong_probe_count(tmp_path: Path) -> None:
    csv_path = tmp_path / "results.csv"
    csv_path.write_text(
        "case_id,pass\none,True\n",
        encoding="utf-8",
    )
    with pytest.raises(HarnessHonestyInputError, match="expected 10 probes"):
        load_privacy_fuzz_pass_rate(csv_path)


@pytest.mark.unit
def test_privacy_fuzz_pass_rate_all_pass() -> None:
    rows = FIXTURES / "privacy_fuzz_all_pass.csv"
    rows.write_text(
        "case_id,pass\n"
        + "\n".join(f"p{i},True" for i in range(10))
        + "\n",
        encoding="utf-8",
    )
    try:
        _, total, rate = load_privacy_fuzz_pass_rate(rows)
        assert total == 10
        assert rate == pytest.approx(1.0)
    finally:
        rows.unlink(missing_ok=True)


@pytest.mark.unit
def test_privacy_fuzz_pass_rate_partial() -> None:
    passes, total, rate = load_privacy_fuzz_pass_rate(FIXTURES / "privacy_fuzz_results.csv")
    assert passes == 9
    assert total == 10
    assert rate == pytest.approx(0.9)


@pytest.mark.unit
def test_render_latex_structure() -> None:
    metrics = HarnessHonestyMetrics(
        leakage_score=0.111,
        procedural_independence=1.0,
        distributional_independence=0.222,
        ground_truth_stability_mean=0.4967,
        privacy_fuzz_pass_rate=0.9,
        privacy_fuzz_probe_count=10,
        governance_compliance_score=0.44,
        decision_traceability=1.0,
        mean_path_trust=0.333,
    )
    tex = render_harness_honesty_latex(metrics)
    assert "\\label{tab:harness-honesty}" in tex
    assert tex.count("&") >= 7
    assert "\\toprule" in tex
    assert "\\bottomrule" in tex
    assert AUTO_GENERATED_BANNER.strip() in tex


@pytest.mark.unit
def test_render_no_hardcoded_reference_values() -> None:
    metrics = HarnessHonestyMetrics(
        leakage_score=0.111,
        procedural_independence=1.0,
        distributional_independence=0.222,
        ground_truth_stability_mean=0.4967,
        privacy_fuzz_pass_rate=0.9,
        privacy_fuzz_probe_count=10,
        governance_compliance_score=0.44,
        decision_traceability=1.0,
        mean_path_trust=0.333,
    )
    tex = render_harness_honesty_latex(metrics)
    assert "0.111" in tex
    assert "0.300" not in tex
    assert "0.333" in tex
    assert "0.060" not in tex


@pytest.mark.unit
def test_export_writes_file(tmp_path: Path) -> None:
    metrics = HarnessHonestyMetrics(
        leakage_score=0.3,
        procedural_independence=1.0,
        distributional_independence=0.698,
        ground_truth_stability_mean=0.5,
        privacy_fuzz_pass_rate=1.0,
        privacy_fuzz_probe_count=10,
        governance_compliance_score=0.44,
        decision_traceability=1.0,
        mean_path_trust=0.06,
    )
    out = tmp_path / "harness_honesty.tex"
    export_harness_honesty_tex(out, metrics=metrics)
    assert out.is_file()
    assert out.read_text(encoding="utf-8").startswith("% Auto-generated by dualexis")


def parse_harness_honesty_values(tex: str) -> dict[str, float]:
    pattern = re.compile(r"^\s+.+?&\s*([0-9.]+)\s*\\\\\s*$", re.MULTILINE)
    keys = [
        "leakage_score",
        "procedural_independence",
        "distributional_independence",
        "privacy_fuzz_pass_rate",
        "governance_compliance",
        "decision_traceability",
        "mean_path_trust",
    ]
    values = [float(match.group(1)) for match in pattern.finditer(tex)]
    return dict(zip(keys, values, strict=True))
